server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/Spring
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: GMT+4
  flyway:
    enabled: true
    url: jdbc:postgresql://127.0.0.1:5433/Spring
    user: postgres
    password: 1
  graphql:
    graphiql:
      enabled: false
  security:
    user:
      name: 1
      password: 1
  rabbitmq:
    host: 10.100.10.248
    port: 5672
    username: guest
    password: guest
logging:
  level:
    root: INFO